imports:
    - { resource: framework_prod.yml }

framework:
    profiler:
        # Collect profiles only on exceptions to prevent memory exhaustion on heavy but successful requests
        only_exceptions: true
