version: "3.7"

services:
  web:
    container_name: dgcs-claroline-web
    build:
      context: .
      dockerfile: .docker.dev/web/Dockerfile
    ports:
      - "8088:80"
      - "8443:443"
    volumes:
      - ./:/var/www/html/claroline
      - claroline_vendor:/var/www/html/claroline/vendor
      - claroline_cache:/var/www/html/claroline/var/cache
      - claroline_log:/var/www/html/claroline/var/log
      - claroline_geoip:/var/www/html/claroline/var/geoip
    depends_on:
      - db
      - mailhog
    environment:
      - APP_URL=claroline.example.com
      - ENV=DEV
      - APP_ENV=dev
      - APP_DEBUG=0
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=4096
      - WEBPACK_DEV_SERVER=0
      - GEOIP_DISABLE=1
      - SKIP_REBUILD=1
      - DB_HOST=dgcs-claroline-db
      - DB_NAME=claroline
      - DB_USER=claroline
      - DB_PASSWORD=claroline
      - SECRET="secret-claroline"
      - ADMIN_FIRSTNAME=John
      - ADMIN_LASTNAME=Doe
      - ADMIN_USERNAME=root
      - ADMIN_PASSWORD=claroline
      - ADMIN_EMAIL=claroline@example.com
      - PLATFORM_NAME=Claroline
      - PLATFORM_SUPPORT_EMAIL=claroline@example.com
      - MAILER_DSN=smtp://mailhog:1025
    networks:
      claroline_network:
        ipv4_address: 172.22.9.6

  db:
    container_name: dgcs-claroline-db
    environment:
      MYSQL_ROOT_PASSWORD: claroline
      MYSQL_USER: claroline
      MYSQL_PASSWORD: claroline
      MYSQL_DATABASE: claroline
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - ../mysql:/var/lib/mysql
      - ./.docker.dev/mysql:/etc/mysql/conf.d
    networks:
      claroline_network:
        ipv4_address: 172.22.9.5

  mailhog:
    container_name: dgcs-claroline-mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      claroline_network:
        ipv4_address: 172.22.9.7

networks:
  claroline_network:
    ipam:
      config:
        - subnet: 172.22.9.0/24

volumes:
  claroline_vendor:
  claroline_cache:
  claroline_log:
  claroline_geoip:
