# Base directories used by the transfer bundle.
parameters:
    claroline.transfer.files_dir: "%claroline.param.files_directory%/transfer"
    claroline.transfer.logs_dir: "%claroline.param.import_log_dir%"
