# Storage paths for icon sets managed at runtime.
parameters:
    claroline.param.icon_sets_directory: "%claroline.param.public_files_directory%/icon_sets"
    claroline.param.icon_sets_web_dir: "%claroline.param.data_web_dir%/icon_sets"
