#!/usr/bin/env php
<?php

declare(strict_types=1);

use Claroline\CursusBundle\Entity\Course;
use Claroline\CursusBundle\Entity\Event;
use Claroline\CursusBundle\Entity\Session;
use Claroline\KernelBundle\Kernel;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\InputDefinition;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Style\SymfonyStyle;

require dirname(__DIR__) . '/vendor/autoload.php';

$definition = new InputDefinition([
    new InputOption('env', null, InputOption::VALUE_OPTIONAL, 'Symfony environment', getenv('APP_ENV') ?: 'dev'),
    new InputOption('courses', null, InputOption::VALUE_OPTIONAL, 'Number of courses to create', 2),
    new InputOption('sessions', null, InputOption::VALUE_OPTIONAL, 'Sessions per course', 2),
    new InputOption('events', null, InputOption::VALUE_OPTIONAL, 'Events per session', 2),
    new InputOption('prefix', null, InputOption::VALUE_OPTIONAL, 'Code prefix used for generated entities', 'DEMO'),
    new InputOption('reset', null, InputOption::VALUE_NONE, 'Erase existing demo entries before seeding'),
]);

$input = new ArgvInput(null, $definition);
$output = new ConsoleOutput();
$io = new SymfonyStyle($input, $output);

$env = $input->getOption('env') ?? 'dev';
$debug = filter_var(getenv('APP_DEBUG') ?? ($env !== 'prod'), FILTER_VALIDATE_BOOLEAN);
$courses = max(1, (int) $input->getOption('courses'));
$sessions = max(1, (int) $input->getOption('sessions'));
$events = max(0, (int) $input->getOption('events'));
$prefix = strtoupper((string) $input->getOption('prefix'));
$reset = (bool) $input->getOption('reset');

$kernel = new Kernel($env, $debug);
$kernel->boot();

try {
    /** @var EntityManagerInterface $em */
    $em = $kernel->getContainer()->get('doctrine')->getManager();

    $io->title('Claroline demo cursus seeder');
    $io->text(sprintf(
        'Environment: %s, Courses: %d, Sessions/course: %d, Events/session: %d, Prefix: %s',
        $env,
        $courses,
        $sessions,
        $events,
        $prefix
    ));

    if ($reset) {
        purgeDemoData($em, $prefix, $io);
    }

    seedDemoData($em, $courses, $sessions, $events, $prefix, $io);
    $io->success('Cursus demo data ready.');
} catch (\Throwable $exception) {
    $io->error($exception->getMessage());
    $kernel->shutdown();
    exit(1);
}

$kernel->shutdown();

function purgeDemoData(EntityManagerInterface $em, string $prefix, SymfonyStyle $io): void
{
    $wildcard = sprintf('%s-%%', $prefix);
    $io->section(sprintf('Purging existing %s demo entities', $prefix));

    foreach ([Event::class, Session::class, Course::class] as $class) {
        $items = $em->createQueryBuilder()
            ->select('e')
            ->from($class, 'e')
            ->where('e.code LIKE :prefix')
            ->setParameter('prefix', $wildcard)
            ->getResult();

        if (empty($items)) {
            continue;
        }

        foreach ($items as $entity) {
            $em->remove($entity);
        }

        $em->flush();
        $io->writeln(sprintf('Removed %d %s rows', count($items), (new \ReflectionClass($class))->getShortName()));
    }
}

function seedDemoData(
    EntityManagerInterface $em,
    int $courseCount,
    int $sessionsPerCourse,
    int $eventsPerSession,
    string $prefix,
    SymfonyStyle $io
): void {
    $baseDate = new \DateTime('now');
    $io->section('Creating demo trainings');
    $courseRepository = $em->getRepository(Course::class);

    for ($courseIndex = 1; $courseIndex <= $courseCount; $courseIndex++) {
        $course = new Course();
        $courseCode = sprintf('%s-C%02d', $prefix, $courseIndex);

        if ($courseRepository->findOneBy(['code' => $courseCode])) {
            $io->writeln(sprintf(' - %s already exists, skipping', $courseCode));
            continue;
        }

        $course->setCode($courseCode);
        $course->setSlug(strtolower($courseCode));
        $course->setName(sprintf('Demo Course %02d', $courseIndex));
        $course->setPlainDescription('Automatically generated by scripts/seed-cursus.php');
        $course->setPublicRegistration(true);
        $course->setAutoRegistration(true);
        $course->setRegistrationMail(true);
        $em->persist($course);
        $io->writeln(sprintf(' - %s', $courseCode));

        for ($sessionIndex = 1; $sessionIndex <= $sessionsPerCourse; $sessionIndex++) {
            $session = new Session();
            $sessionCode = sprintf('%s-C%02d-S%02d', $prefix, $courseIndex, $sessionIndex);
            $session->setCode($sessionCode);
            $session->setCourse($course);
            $session->setName(sprintf('Session %02d.%02d', $courseIndex, $sessionIndex));
            $session->setPlainDescription('Demo session generated for local testing.');
            $session->setPublicRegistration(true);
            $session->setAutoRegistration(true);
            $session->setDefaultSession($sessionIndex === 1);

            $sessionStart = (clone $baseDate)->modify(sprintf('+%d days', ($courseIndex - 1) * $sessionsPerCourse + $sessionIndex));
            $sessionEnd = (clone $sessionStart)->modify('+2 hours');
            $session->setStartDate($sessionStart);
            $session->setEndDate($sessionEnd);

            $em->persist($session);
            $io->writeln(sprintf('   - %s (%s -> %s)', $sessionCode, $sessionStart->format('Y-m-d H:i'), $sessionEnd->format('Y-m-d H:i')));

            for ($eventIndex = 1; $eventIndex <= $eventsPerSession; $eventIndex++) {
                $event = new Event();
                $eventCode = sprintf('%s-E%02d-%02d-%02d', $prefix, $courseIndex, $sessionIndex, $eventIndex);
                $event->getPlannedObject();
                $event->setCode($eventCode);
                $event->setSession($session);
                $event->setName(sprintf('Event %02d.%02d.%02d', $courseIndex, $sessionIndex, $eventIndex));
                $event->setDescription('Auto-generated event slot');

                $eventStart = (clone $sessionStart)->modify(sprintf('+%d hours', $eventIndex));
                $eventEnd = (clone $eventStart)->modify('+1 hour');
                $event->setStartDate($eventStart);
                $event->setEndDate($eventEnd);

                $em->persist($event);
                $io->writeln(sprintf('     * %s (%s)', $eventCode, $eventStart->format('Y-m-d H:i')));
            }
        }
    }

    $em->flush();
}
