<?php

/*
 * This file is part of the Claroline Connect package.
 *
 * (c) Claroline Consortium <consortium@claroline.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Claroline\CoreBundle\Twig;

use Symfony\Bridge\Twig\Extension\AssetExtension;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

class WebpackExtension extends AbstractExtension
{
    private $assetExtension;
    private $environment;
    private $projectDir;
    private $assetCache;

    public function __construct(AssetExtension $extension, string $environment, string $projectDir)
    {
        $this->assetExtension = $extension;
        $this->environment = $environment;
        $this->projectDir = $projectDir;
    }

    public function getFunctions()
    {
        return [
            'hotAsset' => new TwigFunction('hotAsset', [$this, 'hotAsset']),
        ];
    }

    public function getName()
    {
        return 'webpack_extension';
    }

    /**
     * Returns the URL of an asset managed by webpack. The final URL will depend
     * on the environment and the version hash generated by webpack.
     *
     * @param string $path
     * @param bool   $hot
     *
     * @return string
     *
     * @throws \Exception
     */
    public function hotAsset($path, $hot = true)
    {
        $assets = $this->getWebpackAssets();
        $assetName = pathinfo($path, PATHINFO_FILENAME);

        if (!isset($assets[$assetName])) {
            $assetNames = implode("\n", array_keys($assets));

            throw new \Exception("Cannot find asset '{$assetName}' in webpack stats. Found:\n{$assetNames})");
        }

        // Honour WEBPACK_DEV_SERVER=0 to force static assets even in dev.
        // Symfony loads .env values into $_SERVER / $_ENV, but not always into getenv().
        $useDevServer = 'dev' === $this->environment && $hot && $this->isWebpackDevServerEnabled();

        if ($useDevServer) {
            // for dev serve fill from webpack-dev-server
            return 'http://localhost:8080/dist/'.$assets[$assetName]['js'];
        }

        // otherwise serve static generated files
        return $this->assetExtension->getAssetUrl(
            'dist/'.$assets[$assetName]['js']
        );
    }

    private function getWebpackAssets()
    {
        if (!$this->assetCache) {
            $assetFile = 'prod'; // for prod and test envs

            // In dev, fall back to the dev manifest only when the dev server is enabled
            if ('dev' === $this->environment && $this->isWebpackDevServerEnabled()) {
                $assetFile = 'dev';
            }

            $assetFile = "{$this->projectDir}/webpack-{$assetFile}.json";

            if (!file_exists($assetFile)) {
                throw new \Exception(sprintf('Cannot find webpack generated assets file(s). Make sure you '.'have ran webpack with assets-webpack-plugin enabled'));
            }

            $this->assetCache = json_decode(file_get_contents($assetFile), true);
        }

        return $this->assetCache;
    }

    private function isWebpackDevServerEnabled(): bool
    {
        $value = $this->readEnvValue('WEBPACK_DEV_SERVER');

        if (null === $value) {
            $value = $_SERVER['WEBPACK_DEV_SERVER'] ?? $_ENV['WEBPACK_DEV_SERVER'] ?? null;
        }

        return in_array((string) $value, ['1', 'true', 'yes', 'on'], true);
    }

    private function readEnvValue(string $name): ?string
    {
        foreach (['.env.local', '.env'] as $filename) {
            $path = sprintf('%s/%s', $this->projectDir, $filename);

            if (!is_file($path)) {
                continue;
            }

            foreach (file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
                $line = trim($line);

                if ('' === $line || str_starts_with($line, '#')) {
                    continue;
                }

                if (str_starts_with($line, $name.'=')) {
                    return trim(substr($line, \strlen($name) + 1), "\"'");
                }
            }
        }

        return null;
    }
}
