<?php

/*
 * This file is part of the Claroline Connect package.
 *
 * (c) Claroline Consortium <consortium@claroline.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Claroline\CoreBundle\Twig;

use Symfony\Bridge\Twig\Extension\AssetExtension;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

class WebpackExtension extends AbstractExtension
{
    private $assetExtension;
    private $environment;
    private $projectDir;
    private $assetCache;

    public function __construct(AssetExtension $extension, string $environment, string $projectDir)
    {
        $this->assetExtension = $extension;
        $this->environment = $environment;
        $this->projectDir = $projectDir;
    }

    public function getFunctions()
    {
        return [
            'hotAsset' => new TwigFunction('hotAsset', [$this, 'hotAsset']),
        ];
    }

    public function getName()
    {
        return 'webpack_extension';
    }

    /**
     * Returns the URL of an asset managed by webpack. The final URL will depend
     * on the environment and the version hash generated by webpack.
     *
     * @param string $path
     * @param bool   $hot
     *
     * @return string
     *
     * @throws \Exception
     */
    public function hotAsset($path, $hot = true)
    {
        $assets = $this->getWebpackAssets();
        $assetName = pathinfo($path, PATHINFO_FILENAME);

        if (!isset($assets[$assetName])) {
            $assetNames = implode("\n", array_keys($assets));

            throw new \Exception("Cannot find asset '{$assetName}' in webpack stats. Found:\n{$assetNames})");
        }

        // Only use webpack-dev-server in dev when explicitly enabled.
        $devServerEnabled = getenv('WEBPACK_DEV_SERVER');
        $useHot = ('dev' === $this->environment) && $hot && (false !== $devServerEnabled) && in_array(strtolower((string) $devServerEnabled), ['1', 'true', 'yes'], true);
        if ($useHot) {
            // for dev serve file from webpack-dev-server
            return 'http://localhost:8080/dist/'.$assets[$assetName]['js'];
        }

        // otherwise serve static generated files
        return $this->assetExtension->getAssetUrl(
            'dist/'.$assets[$assetName]['js']
        );
    }

    private function getWebpackAssets()
    {
        if (!$this->assetCache) {
            // In dev, prefer dev manifest only when dev-server is enabled.
            $assetFile = 'prod'; // default for prod/test and for dev without dev-server
            $devServerEnabled = getenv('WEBPACK_DEV_SERVER');
            $useHot = ('dev' === $this->environment) && (false !== $devServerEnabled) && in_array(strtolower((string) $devServerEnabled), ['1', 'true', 'yes'], true);
            if ($useHot) {
                $assetFile = 'dev';
            }

            $assetFile = "{$this->projectDir}/webpack-{$assetFile}.json";

            if (!file_exists($assetFile)) {
                throw new \Exception(sprintf('Cannot find webpack generated assets file(s). Make sure you '.'have ran webpack with assets-webpack-plugin enabled'));
            }

            $this->assetCache = json_decode(file_get_contents($assetFile), true);
        }

        return $this->assetCache;
    }
}
